### PR TITLE
Fix find_primary_index

### PR DESCRIPTION
**Pull request by saindriches**
Always check PREDEFINED_COLORSPACE_PRIMARIES.

### CODE REVIEW

**Comment by saindriches** [comment]
This should be the correct way. For some reason, there is also a P3D65 field in PREDEFINED_REALDEVICE_PRIMARIES, we need to check PREDEFINED_COLORSPACE_PRIMARIES first, to avoid picking that for L10.

**Comment by quietvoid** [comment]
Thanks I'll try experimenting with this to understand more.

**Comment by quietvoid** [comment]
I still don't really know where the real device primaries come from.
For predefined primaries I guess you might've tried different coordinates to see if they're allowed as L9 presets.  
Since the verifier validates the primaries match.

However for L10 there doesn't seem to be such validation with `target_primary_index`.
So I don't really know how you verified this.

I did learn that L8 and L10 can conflict if they have the same `target_max_pq`, too.

**Comment by saindriches** [comment]
The real device primaries is only for L9, so an index from 0 to 18 is accepted in L9, only 0-8 is accepted in L10. I figured out the values from binary.

**Comment by quietvoid** [comment]
Alright well I at least can verify that it's indeed limited to the preset values you said.
So I guess I'll just merge this, the logic looks fine.

Thanks.

**Pull request merged**
