### PR TITLE
Experimental profile 5 to 8 conversion

### PR DESCRIPTION
**Pull request by quietvoid**
Need to test on more samples.

### CODE REVIEW

**Comment by quietvoid** [comment]
Tested on one working sample with `inject-rpu` and it played back fine.

**Comment by ValZapod** [comment]
You tested this on both non HDR10 compativle (i.e. using IPTPQc2) profile 5 and HDR10 compatible profile 5?

**Comment by quietvoid** [comment]
> HDR10 compatible profile 5?

What does this mean? Profile 5 is always IPT PQ.

The conversion only makes it possible to use the RPU from a profile 5 file for a HDR10 version of the same title.

**Comment by ValZapod** [comment]
> Profile 5 is always IPT PQ, so never HDR10 compatible.

No, it is not. For example see Apple 4K screensavers https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit?usp=drivesdk

or even this full rip of movie Overlord from stream platform with info hash: 
 93ac3b3e8fdf72301ceaad905edd31ab24ff5954 (mediainfo https://controlc.com/ca5ca466)
The difference is that IPTPQc2 is full range, has no HDR10 metadata and is not tagged as HDR10 compatible, while the opposite is true for HDR10 profile 5.

**Comment by quietvoid** [comment]
> The difference is that IPTPQc2 is full range, has no HDR10 metadata and is not tagged as HDR10 compatible, while the opposite is true for HDR10 profile 5.
According to the Dolby docs:
> Within the Dolby Vision context, a profile 5 bitstream must use perceptual quantization withreshaping for EOTF; uses Dolby Vision proprietary IPT color space for color primaries and colormatrix; uses full range for range; and uses center-left siting for chroma sample location.

So it must be IPT and PQ, as well as full range.
You have to realize that MP4s are parsed by MediaInfo according to the DOVI config record, not the actual RPU.

**Comment by ValZapod** [comment]
> According to the Dolby docs:

Apple uses its own specs. Though latest 1.3.2 version of docs does describe the new HLG profile 8.

> I need more precision to which sample

All HDR ones, for example https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_HDR_FINAL_20180709_HDR_4K_HEVC.mov

**Comment by quietvoid** [comment]
>  Apple uses its own specs for .mov. Though latest 1.3.2 version of docs does describe the new HLG profile 8.
I'm aware of the HLG profile 8.
What I want is specifications for what you're describing as non-IPT profile 5, which goes against the docs I'm using.

If you have no official info or document, then this conversation leads to nowhere.
I'm not comparing RPUs based on single files with no backing specification.

**Comment by ValZapod** [comment]
> If you have no official info or document, then this conversation leads to nowhere.

Well, LOL, see for yourself https://www.google.com/search?q=Dolby+Vision+mov+spec+apple.com+%22profile+5%22

"(Profile 5)/HDR10" Also, mov is "just" mp4... Just like webm is "just" mkv.

Also, were you to have LG C9 with reference implementation... It plays those correctly and does not force reshaping and stuff.

Also, I doubt you need to parse RPU, just check for what Mediainfo checks for.

But yeah, 
https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C011_PSNK_v02_HDR_FINAL_20180709_HDR_4K_HEVC.mov looks like requires parsing RPU, as reference windows 10 UWP apps (two apps plus Zune Player, a.k.a. movies and TV) do. Since Mediainfo does not show it as HDR10 compatible, but it is.

> I'm not comparing RPUs based on single files with no backing specification

There is docs in the patent, you know.

**Comment by ValZapod** [comment]
BTW, are you going to check on something more good, using IPTPQc2? Like on The Mandalorian, The winter soldier or The Avengers: endgame?? I mean, what

>working sample with inject-rpu 

was that? Was is big enough? Did you check version 4 DV metadata? :)

**Comment by quietvoid** [comment]
> "(Profile 5)/HDR10" Also, mov is "just" mp4... Just like webm is "just" mkv.

This does not clearly define support for a profile 5 + HDR10 compatible stream, just support for both of the formats.

> Also, I doubt you need to parse RPU, just check for what Mediainfo checks for.

You can mux MP4 with any Dolby Vision configuration box, which is what MediaInfo checks.
So using the MP4 configuration doesn't mean much.

So far all the samples you mentioned are confusing info in the RPU.
The base layer has limited RGB range, while the RPU is basically profile 5 and says that it's full range.
There is no reshaping info.

To me it just looks like a messed up conversion from profile 5 to profile 8, since there is no specification document.
I still wouldn't say that it's a real profile 5 because all the info is contrary to the Dolby specs.

> BTW, are you going to check on something more good, using IPTPQc2? Like on The Mandalorian, The winter soldier or The Avengers: endgame?? I mean, what

IPT PQ RPU files are already supported by this feature.

> was that? Was is big enough? Did you check version 4 DV metadata? :)

Yes it was a full length title.
There are no publicly available CMv4 specifications, so it's impossible to know which is what.
All the RPU parsing is based on Blu-ray spec, which is only version CMv2.9.

**Comment by ValZapod** [comment]
BTW. Two samples (VFR, one is 60 fps) from iPhone 11 (profile 8 and strange level, which IS AGAIN not defined by the specification, so...)
https://drive.google.com/file/d/1cTRNwacsV-8J8PtcYNVDXBmGZF1SOynj/view?usp=sharing

And iPhone 12 sample (again strange level):
https://drive.google.com/file/d/1JsFd_KKU0k5Emgl74PnrwmUfqdFDP9JJ/view?usp=sharing

>All the RPU parsing is based on Blu-ray spec, which is only version CMv2.9.

LOL, but that does not support IPTPQc2.

> The base layer has limited RGB range, while the RPU is basically profile 5 and says that it's full range.

Limited YCbCr, you mean. And, what are you saying is that RPU signales IPTPQc2? Which are signaled by ycc_to_rgb_coefx and rgb_to_lms_coefx, I suppose.

**Comment by quietvoid** [comment]
> profile 8 and strange level, which IS AGAIN not defined by the specification, so...
The level is not strange, it's level 12.
Who knows why it was set level 12 though.

> LOL, but that does not support IPTPQc2.
Yet the RPU format is exactly the same for all the samples I tried. So it doesn't matter.

> Limited YCbCr, you mean. And, what are you saying is that RPU signales IPTPQc2? Which are signaled by ycc_to_rgb_coefx and rgb_to_lms_coefx, I suppose.

Yes. It only signals IPT, which is expected to be along a PQ EOTF according to the specs.

**Comment by ValZapod** [comment]
> The level is not strange, it's level 12.

Yeah, I know what is it in hex, thank you very much. Two levels are 0A and 0C.

> To me it just looks like a messed up conversion from profile 5 to profile 8, since there is no specification document.

Okay, if the RPU has LMS stuff the same as that for IPTPQ with c==2, then it is wrong for sure. If you can confirm that, we can just conclude that Apple are just dummies (though interesting that it does not see it as IPTPQc2, is it just limited range check? Will have to check).

**Comment by quietvoid** [comment]
The profile 5, HDR10 limited files from Apple all do not have IPT coefficients as expected from profile 5 IPT encoded files.
And the coefficient values are the same as HDR10 streams like profile 7 and 8.

You can confirm all of this easily with `dovi_tool info -i RPU.bin -f 0` after extracting the RPU from any file.

**Comment by ValZapod** [comment]
> The profile 5, HDR10 limited files from Apple all do not have IPT coefficients as expected from profile 5 IPT encoded files

Then Apple are not dummies and HDR10 in apple is supported.

**Comment by quietvoid** [comment]
Not until there's official documentation for it.

All the signs point towards an incorrect profile, both according to the Dolby specs as well as mismatching base layer and RPU information.

**Comment by ValZapod** [comment]
> specs as well as mismatching base layer and RPU information.

So there is a mismatch after all? Sigh, will have to compile dovi_tool myself. Oogh.

**Comment by mstattma** [comment]
Do I understand this correctly as Apple devices basically playing profile 8.1 when (mis)labeled as profile 5 in the decoder config record?

**Comment by ValZapod** [comment]
> understand this correctly as Apple devices basically playing profile 8.1 when 

Maybe. Because that is the profile used by Apple 4K they though they can use it for non-IPTPQc2. Not surprising how hard it was for them to fix 24.000 fps video vs 24/1.001 and how hard it was for them to fix rised blacks in DV.

@quietvoid Okay I will have to read ETSI and patents again to understand whether 

While there there are two warning that compiler produces about aud being unused function :)

**Comment by quietvoid** [comment]
> Do I understand this correctly as Apple devices basically playing profile 8.1 when (mis)labeled as profile 5 in the decoder config record?

@mstattma Apple TV 4K devices have always only supported profile 5 only, so it is quite likely why they are doing it this way.
At first, `yusesope`'s script would modify RPUs to emulate profile 5 for them. That has changed to profile 8 afterwards.

> BTW, dovi_tool cannot parse all metadata properly...

If something was parsed incorrectly, the CRC32 hash verification would fail. So far it has not.
If you find a problem, open a new issue.

**Comment by ValZapod** [comment]
> If something was parsed incorrectly, the CRC32 hash verification would fail

I mean it says there left over bytes. CRC passes.

**Comment by quietvoid** [comment]
Remaining bytes are either unknown or simply kept to keep the RPU rewriting lossless.
There's no easy way to reverse engineer what they mean without documentation, if that's what you're after.

**Comment by ValZapod** [comment]
> Remaining bytes are either unknown or simply kept in memory to keep the RPU rewriting lossless.

Yes, I know how CRC32 works. As well as most other hash functions.

> There's no easy way to reverse engineer what they mean without documentation, if that's what you're after.

There is a documentation. In SMPTE docs, in many patents and in ETSI specs.

**Comment by quietvoid** [comment]
So open a new issue for support with relevant links.
Obviously you know more than I do.

**Comment by ValZapod** [comment]
> So open a new issue for support with relevant links.
> Obviously you know more than I do.

Are those

```
remaining: BitVec<bitvec::order::Msb0, u8> {
        addr: 0x000055e78c4c0660,
        head: 000,
        bits: 7,
        capacity: 64,
    } [
        0b0000000,
    ],

```
 indeed not parsed because you do not know what is in them?

It looks like there are multiple unknown in multiple trims of L2 (ExtMetadataBlockLevel2) (and no in L6) and one in the end.

**Comment by quietvoid** [comment]
No, it's to respect the RPU specifications:

```
while ( ext_block_use_bits ++ < ext_block_ len_bits )
    ext_dm_alignment_zero_bit      f(1)
```

Because the data has to be byte-aligned.

However there are titles with more data left over after parsing.
One of those is a test file named `data_before_crc32.bin`

**Comment by Boodax78** [comment]
Thanks, it works perfectly on my lg oled CX tv

web hbo max file 1 

Format profile: Main 10@L5@Main
HDR format: Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID: dvhe
Codec ID/Info: High Efficiency Video Coding with Dolby Vision
Length: 1 hr 51 min
Bit rate : 17,9 Mb/s

web hbo max file 2 (same movie)

HDR format: SMPTE ST 2086, HDR10 compatible
Codec ID: V_MPEGH/ISO/HEVC
Duration : 1 h 51 min
Bitrate : 17.9 Mb/s

I applied the "assets" "p5_to_p81.json" to modify the rpu. 

And I ripped FILE 2 with x265 and RPU_modified.

x265.exe --bitrate 17900 --preset ultrafast --output-depth 10 --vbv-bufsize 24500 --vbv-maxrate 24500 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --hdr10 --colorprim bt2020 --colormatrix bt2020nc --range limited --chromaloc 2 --dolby-vision-profile 8.1 --dolby-vision-rpu D:\Downloads\incoming\dovitools\RPU_modified.bin --repeat-headers --output "D:\Downloads\torrents reception\TestDolbyVisionMKV-MP4\test.hevc" "

**Pull request merged**
