### PR TITLE
Refactor extension metadata blocks

### PR DESCRIPTION
**Pull request by quietvoid**
As well as standardizing the RPU generation.

Left to do:
- [x] Fix C API
- [x] Fix generator documentation
- [x] Add new tests
- [x] Add more levels support in XML parser

### CODE REVIEW

**Comment by saindriches** [comment]
Is there any sample RPU matching the L11 struct, or any public information about the so many entries? Since only `content_type` and `white_point` are included in metadata.

**Comment by quietvoid** [comment]
> Is there any sample RPU matching the L11 struct, or any public information about the so many entries? Since only `content_type` and `white_point` are included in metadata.

At the moment I'm still trying to figure out the format, using the Dolby verifier as help.
The current implementation is based on https://patents.google.com/patent/WO2020264409A1
But it seems incorrect.

I haven't seen a sample using it yet.

**Comment by saindriches** [comment]
The L11 block from iPhone recorded video includes:
```
content_type = 4
white_point = 0
reference _mode_flag = 0
(rest of byte2)
(byte3)
```
Seems the length is correct, but they only use these entries for now.

Content type 4 is User-generated content (While the meaning of 0-3 matches patent, 5-15 are reserved), and the function to calculate color temp is `white_point * 375 + 6504`, so maybe 0 means 6504K.

**Comment by quietvoid** [comment]
Alright I found a sample with everything, will try to fix it.

**Comment by quietvoid** [comment]
Well, it doesn't like the reference mode flag. Presumably because it's always set to 0.

**Comment by quietvoid** [comment]
I did end up figuring it out.
For reference mode, we need to add 16 to the whitepoint.

**Comment by quietvoid** [comment]
I'm not sure what the L10 and L11 format is in XML.

**Pull request merged**
