### PR TITLE
Fix RPU header parsing for Profile 7

### LINKED ISSUE #131: Part of '"num_x_partitions_minus1": 2046' should be parsed as nlq_pred_pivot_value
From metafier:
```
  |  nlq_method_idc                            0
  |  nlq_num_pivots                            2
  |  nlq_pred_pivot_value                        0 1023
  |  partitions                                y: 1  x: 1

```

While you parse it as 

    "nlq_method_idc": 0,
    "nlq_num_pivots_minus2": 0,
    "num_x_partitions_minus1": 2046,
    "num_y_partitions_minus1": 0

### PR DESCRIPTION
**Pull request by saindriches**
Add the missing nlq_pred_pivot_value for it.
Fix #131 #132, sorry for forgetting to check tests.

### CODE REVIEW

**Comment by quietvoid** [comment]
What would lead to believe this is actually in the bitstream?
Nothing breaks because it's hardcoded to 0, what about other values?

**Comment by ValZapod** [comment]
> What would lead to believe this is actually in the bitstream?

Partition being 2067 is wrong. Howoever you look at it. I remember reading about it, but yesterday did not find it.

**Comment by saindriches** [comment]
We don’t know why nlq_pred_pivot_value is existed in Profile 7 bitstream, seems unnecessary. But pretty sure partition is 1 for all current profiles. So exp-golomb code 2046 is actually 3 values, and it matches verifier with fix.

**Comment by ValZapod** [comment]
>We don’t know why nlq_pred_pivot_value is existed in Profile 7 bitstream

Dolby Metafier omits these on not profile 7 (I think it looks into el_spatial_resampling_filter_flag and  disable_residual_flag).

```
nlq_method_idc                            0
  |  nlq_num_pivots                            2
  |  nlq_pred_pivot_value                        0 1023
```

Of course in 8 profile those values are still there.

**Comment by saindriches** [comment]
> Of course in 8 profile those values are still there.

NLQ things only exist in profiles with EL, and profile 8 bitstream doesn’t have it.

**Comment by ValZapod** [comment]
> and profile 8 bitstream doesn’t have it.

AFAIK it is allowed. Yes, I know NLQ is FEL only.

**Comment by quietvoid** [comment]
The changes don't seem to work with values other than zero.

**Comment by saindriches** [comment]
Current value in profile 4/7 is 0 and 1023, it should be able to read and write other values, while the convert_to_mel uses hardcoded `vec![0, 1023]`. Did I miss something?

**Comment by quietvoid** [comment]
It works with `nlq_pred_pivot_value=[0, 1023]` but not `nlq_pred_pivot_value=[1023, 1023]`, for example.

**Comment by saindriches** [comment]
[fel_to_mel_parsed_mode1.bin.zip](https://github.com/quietvoid/dovi_tool/files/8398865/fel_to_mel_parsed_mode1.bin.zip)
A modified ./assets/tests/fel_to_mel.bin, has `vec![1023, 1023]`, should work.

```
    "nlq_method_idc": 0,
    "nlq_num_pivots_minus2": 0,
    "nlq_pred_pivot_value": [
      1023,
      1023
    ],
    "num_x_partitions_minus1": 0,
    "num_y_partitions_minus1": 0
```

**Comment by quietvoid** [comment]
Well yes, it works in `dovi_tool` but Dolby's verifier errors.

**Comment by saindriches** [comment]
Will try to find what's happening later.

**Comment by quietvoid** [comment]
The first pivot value seems to always need to be zero.
It would need validation added. I'm not sure how it related to the bit deptth, though.

**Comment by saindriches** [comment]
We forgot an important thing: it is used to derive `nlq_pivot_index` or something, so accumulated value should not exceed 2^bitdepth - 1. For example `vec![514, 509]` will pass the verifier.

**Comment by quietvoid** [comment]
Seems fine to merge, I'll fix the rest myself.

**Pull request merged**
